### ISSUE TITLE
ValueError: could not convert string to float: '90,90,90'

### ISSUE THREAD

**Issue by qianxin-kxy** [xthua/bacant#8]
### A very useful tool, but I encountered the following problem during the use process and don't know how to handle it

**Code used:**
$ bacant --indir /data/users/kxytry/infile -o outdir

**Error prompt**
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/bacant/bin/bacant", line 33, in <module>
    sys.exit(load_entry_point('BacAnt==3.3.2', 'console_scripts', 'bacant')())
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 1135, in run
    process_dir(blastn_path,indir,resultdir)
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 881, in process_dir
    ident0 = float(ident0)
ValueError: could not convert string to float: '90,90,90'

**Comment by xthua** [comment]
hi,

please update bacant to 3.4.0

conda install -c bacant -c conda-forge -c bioconda bacant=3.4.0



-----原始邮件-----
发件人:qianxin-kxy ***@***.***>
发送时间:2023-06-05 16:20:24 (星期一)
收件人: xthua/bacant ***@***.***>
抄送: Subscribed ***@***.***>
主题: [xthua/bacant] ValueError: could not convert string to float: '90,90,90' (Issue #8)






A very useful tool, but I encountered the following problem during the use process and don't know how to handle it

Code used:
$ bacant --indir /data/users/kxytry/infile -o outdir

Error prompt
Traceback (most recent call last):
File "/data/users/kxy/miniconda3/envs/bacant/bin/bacant", line 33, in
sys.exit(load_entry_point('BacAnt==3.3.2', 'console_scripts', 'bacant')())
File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 1135, in run
process_dir(blastn_path,indir,resultdir)
File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 881, in process_dir
ident0 = float(ident0)
ValueError: could not convert string to float: '90,90,90'

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>





Xiaoting Hua, PhD, Associate Professor
Sir Run Run Shaw Hospital, Zhejiang University School of Medicine,
Qingchundong 3 RD,
Hangzhou 310016, 
China

**Comment by qianxin-kxy** [comment]
### **Thank you for your reply, but the problem still exists**
**This is the entire process of code execution**

(bacant) [kxy@zju ~]$ conda install -c bacant -c conda-forge -c bioconda bacant=3.4.0
Collecting package metadata (current_repodata.json): done
Solving environment: - 
Warning: >10 possible package resolutions (only showing differing packages):
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64::perl-list-moreutils-0.15-pl5.22.0_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::bzip2-1.0.8-h7f98852_4, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::gmp-6.1.2-hf484d3e_1000, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64::libboost-1.67.0-h46d08c1_4
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64::perl-list-moreutils-0.15-pl5.22.0_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::gmp-6.1.2-hf484d3e_1000, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64::libboost-1.67.0-h46d08c1_4, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  ... and othedone


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0



## Package Plan ##

  environment location: /data/users/kxy/miniconda3/envs/bacant

  added / updated specs:
    - bacant=3.4.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.5.7   |       hbcca054_0         145 KB  conda-forge
    openssl-1.1.1u             |       hd590300_0         1.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.0 MB

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates                anaconda/cloud/conda-forge --> conda-forge 
  openssl                        anaconda/cloud/conda-forge --> conda-forge 


Proceed ([y]/n)? y


Downloading and Extracting Packages
                                                                                                                                             
Preparing transaction: done                                                                                                                  
Verifying transaction: done
Executing transaction: done
(bacant) [kxy@zju ~]$ cd /data/users/kxy/kxytry/assembleddata/analysis/transposon_1
(bacant) [kxy@zju transposon_1]$ bacant --indir /data/users/kxy/kxytry/assembleddata/tog/infile -o outdir
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/bacant/bin/bacant", line 33, in <module>
    sys.exit(load_entry_point('BacAnt==3.3.2', 'console_scripts', 'bacant')())
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 1135, in run
    process_dir(blastn_path,indir,resultdir)
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 881, in process_dir
    ident0 = float(ident0)
ValueError: could not convert string to float: '90,90,90'(bacant)

**In addition, I have also tried other code, such as the one shown below, but it cannot be successfully run**
(bacant) [kxy@zju transposon_1]$ bacant -n FASTA --indir data/users/kxy/kxytry/assembleddata/tog/infile --identities 80,80,80 --resultdir RESULTDIR
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/bacant/bin/bacant", line 33, in <module>
    sys.exit(load_entry_point('BacAnt==3.3.2', 'console_scripts', 'bacant')())
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 1135, in run
    process_dir(blastn_path,indir,resultdir)
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 881, in process_dir
    ident0 = float(ident0)
ValueError: could not convert string to float: '80,80,80'

**Comment by qianxin-kxy** [comment]
> hi, please update bacant to 3.4.0 conda install -c bacant -c conda-forge -c bioconda bacant=3.4.0
> […](#)
> -----原始邮件----- 发件人:qianxin-kxy ***@***.***> 发送时间:2023-06-05 16:20:24 (星期一) 收件人: xthua/bacant ***@***.***> 抄送: Subscribed ***@***.***> 主题: [xthua/bacant] ValueError: could not convert string to float: '90,90,90' (Issue #8) A very useful tool, but I encountered the following problem during the use process and don't know how to handle it Code used: $ bacant --indir /data/users/kxytry/infile -o outdir Error prompt Traceback (most recent call last): File "/data/users/kxy/miniconda3/envs/bacant/bin/bacant", line 33, in sys.exit(load_entry_point('BacAnt==3.3.2', 'console_scripts', 'bacant')()) File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 1135, in run process_dir(blastn_path,indir,resultdir) File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 881, in process_dir ident0 = float(ident0) ValueError: could not convert string to float: '90,90,90' — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> Xiaoting Hua, PhD, Associate Professor Sir Run Run Shaw Hospital, Zhejiang University School of Medicine, Qingchundong 3 RD, Hangzhou 310016, China

### **Thank you for your reply, but the problem still exists**
**This is the entire process of code execution**

(bacant) [kxy@zju ~]$ conda install -c bacant -c conda-forge -c bioconda bacant=3.4.0
Collecting package metadata (current_repodata.json): done
Solving environment: - 
Warning: >10 possible package resolutions (only showing differing packages):
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64::perl-list-moreutils-0.15-pl5.22.0_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::bzip2-1.0.8-h7f98852_4, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::gmp-6.1.2-hf484d3e_1000, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64::libboost-1.67.0-h46d08c1_4
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64::perl-list-moreutils-0.15-pl5.22.0_0, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64::gmp-6.1.2-hf484d3e_1000, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64::libboost-1.67.0-h46d08c1_4, https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  ... and othedone


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0



## Package Plan ##

  environment location: /data/users/kxy/miniconda3/envs/bacant

  added / updated specs:
    - bacant=3.4.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.5.7   |       hbcca054_0         145 KB  conda-forge
    openssl-1.1.1u             |       hd590300_0         1.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.0 MB

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates                anaconda/cloud/conda-forge --> conda-forge 
  openssl                        anaconda/cloud/conda-forge --> conda-forge 


Proceed ([y]/n)? y


Downloading and Extracting Packages
                                                                                                                                             
Preparing transaction: done                                                                                                                  
Verifying transaction: done
Executing transaction: done
(bacant) [kxy@zju ~]$ cd /data/users/kxy/kxytry/assembleddata/analysis/transposon_1
(bacant) [kxy@zju transposon_1]$ bacant --indir /data/users/kxy/kxytry/assembleddata/tog/infile -o outdir
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/bacant/bin/bacant", line 33, in <module>
    sys.exit(load_entry_point('BacAnt==3.3.2', 'console_scripts', 'bacant')())
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 1135, in run
    process_dir(blastn_path,indir,resultdir)
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 881, in process_dir
    ident0 = float(ident0)
ValueError: could not convert string to float: '90,90,90'(bacant)

**In addition, I have also tried other code, such as the one shown below, but it cannot be successfully run**
(bacant) [kxy@zju transposon_1]$ bacant -n FASTA --indir data/users/kxy/kxytry/assembleddata/tog/infile --identities 80,80,80 --resultdir RESULTDIR
Traceback (most recent call last):
  File "/data/users/kxy/miniconda3/envs/bacant/bin/bacant", line 33, in <module>
    sys.exit(load_entry_point('BacAnt==3.3.2', 'console_scripts', 'bacant')())
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 1135, in run
    process_dir(blastn_path,indir,resultdir)
  File "/data/users/kxy/miniconda3/envs/bacant/lib/python3.7/site-packages/BacAnt-3.3.2-py3.7.egg/BacAnt/bacant.py", line 881, in process_dir
    ident0 = float(ident0)
ValueError: could not convert string to float: '80,80,80'
